spring.datasource.url=jdbc:postgresql://localhost:5432/devicemanager
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=devicemanager
spring.datasource.password=devicemanager