/**
 * Device Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request body for creating a new user inside a group
 */
export interface CreateUserRequest { 
    /**
     * Name of the new user
     */
    name: string;
    /**
     * Password of the new user
     */
    password: string;
}

