/**
 * Device Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Result of validating a group\'s access code
 */
export interface GroupAccessValidationResponse { 
    /**
     * Whether the provided access code is valid
     */
    valid?: boolean;
    /**
     * Validation result message
     */
    message?: string;
}

