/**
 * Device Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Short summary of a group
 */
export interface GroupSummaryResponse { 
    /**
     * Unique identifier of the group
     */
    id?: string;
    /**
     * Name of the group
     */
    name?: string;
}

