/**
 * Device Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Response returned after launching an application
 */
export interface LaunchResponse { 
    /**
     * Launch result message
     */
    message?: string;
}

