/**
 * Device Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents an application item displayed in a menu
 */
export interface MenuItemResponse { 
    /**
     * Unique identifier of the menu item
     */
    id?: string;
    /**
     * Display name of the menu item
     */
    name?: string;
    /**
     * Position index of the item inside the menu
     */
    positionIndex?: number;
}

