/**
 * Device Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MenuItemResponse } from './menuItemResponse';
import { SubMenuResponse } from './subMenuResponse';


/**
 * Detailed representation of a user\'s root menu or submenu
 */
export interface RootMenuResponse { 
    /**
     * Name of the menu
     */
    menuName?: string;
    /**
     * Currently selected wallpaper name
     */
    wallpaperName?: string | null;
    /**
     * Currently selected theme name
     */
    themeName?: string | null;
    /**
     * Applications displayed directly in the menu
     */
    applications?: Array<MenuItemResponse>;
    /**
     * Submenus accessible from the root menu
     */
    subMenus?: Array<SubMenuResponse>;
}

