/**
 * Device Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request body for selecting a wallpaper for a user
 */
export interface SelectWallpaperRequest { 
    /**
     * Identifier of the selected wallpaper
     */
    wallpaperId: string;
}

