/**
 * Device Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request body for selecting a theme for a user
 */
export interface SelectThemeRequest { 
    /**
     * Identifier of the selected theme
     */
    themeId: string;
}

