/**
 * Device Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request body for authenticating a user
 */
export interface UserLoginRequest { 
    /**
     * User password
     */
    password: string;
}

