/**
 * Device Manager API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Short summary of a user
 */
export interface UserSummaryResponse { 
    /**
     * Unique identifier of the user
     */
    id?: string;
    /**
     * Name of the user
     */
    name?: string;
    /**
     * Role of the user
     */
    role?: string;
}

